import sqlite3

def get_connection():
    conn = sqlite3.connect("database.db", check_same_thread=False)
    cursor = conn.cursor()

def crir_Tab():
    
    conn = get_connection()
    cursor = conn.cursor()
    
    cursor.executescript("""
    CREATE TABLE IF NOT EXISTS USUARIO (
        COD_USUARIO INTEGER PRIMARY KEY AUTOINCREMENT,
        LOGIN_USER TEXT UNIQUE,
        SENHA TEXT
    );

    CREATE TABLE IF NOT EXISTS PESSOA (
        COD_PESSOA INTEGER PRIMARY KEY AUTOINCREMENT,
        CPF INTEGER UNIQUE,
        RG INTEGER UNIQUE,
        NOME TEXT,
        TELEFONE INTEGER,
        DT_NASC DATE,
        EMAIL TEXT,
        COD_USUARIO INTEGER,
        FOREIGN KEY (COD_USUARIO) REFERENCES USUARIO(COD_USUARIO) 
    );

    CREATE TABLE IF NOT EXISTS PROFESSORA (
        COD_PROFESSORA INTEGER PRIMARY KEY AUTOINCREMENT,
        COD_PESSOA INTEGER,
        FOREIGN KEY (COD_PESSOA) REFERENCES PESSOA(COD_PESSOA) 
    );

    CREATE TABLE IF NOT EXISTS TURMA (
        COD_TURMA INTEGER PRIMARY KEY AUTOINCREMENT,
        TURMA TEXT NOT NULL,
        COD_PROFESSORA INTEGER,
        FOREIGN KEY (COD_PROFESSORA) REFERENCES PROFESSORA(COD_PROFESSORA)
    );

    CREATE TABLE IF NOT EXISTS ALUNO (
        COD_ALUNO INTEGER PRIMARY KEY AUTOINCREMENT,
        COD_TURMA INTEGER,
        FOREIGN KEY (COD_TURMA) REFERENCES TURMA(COD_TURMA)
    );

    CREATE TABLE IF NOT EXISTS PAIS (
        COD_PAI INTEGER PRIMARY KEY AUTOINCREMENT,
        COD_PESSOA INTEGER,
        COD_ALUNO INTEGER,
        FOREIGN KEY (COD_PESSOA) REFERENCES PESSOA(COD_PESSOA),
        FOREIGN KEY (COD_ALUNO) REFERENCES ALUNO(COD_ALUNO)
    );
    """)

    conn.commit()
    conn.close()